Another try

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -75,7 +75,7 @@ stages:
           Idea2020:
             IDEA_VERSION: 'IC-2020.1.2'
             JDKVersion: '1.11'
-            imageName: 'windows-latest'
+            imageName: 'ubuntu-latest'
 #          IdeaEAP:
 #            IDEA_VERSION: 'LATEST-EAP-SNAPSHOT'
 #            JDKVersion: '1.11'
@@ -109,18 +109,38 @@ stages:
         displayName: Setup Xvfb and Metacity
         condition: ne(variables['imageName'], 'windows-latest')
       - bash: |
-          set -e
+          set -e -o pipefail -u
           cd its
-          mkdir -p build/idea-sandbox/system/log/
-          touch build/idea-sandbox/system/log/idea.log
-          ./gradlew --stacktrace --info -PijVersion=$(IDEA_VERSION) "-PslPluginLocation=$(Agent.BuildDirectory)/staged-plugin/sonarlint-intellij" runIdeForUiTests &
-          sleep 120
-          tail -f -n +1 build/idea-sandbox/system/log/idea.log | while read LOGLINE
-          do
-             echo $LOGLINE
-             [[ "${LOGLINE}" == *"Responding at http://0.0.0.0:8082"* ]] && pkill -P $$ tail
+          source utils.sh
+          log=~/gradlew-runIdeForUiTests.log
+          ./gradlew --stacktrace --info -PijVersion=$(IDEA_VERSION) "-PslPluginLocation=$(Agent.BuildDirectory)/staged-plugin/sonarlint-intellij" runIdeForUiTests >$log 2>&1 &
+          # $! expands to the PID of the last process executed in the background
+          ide_pid=$!
+
+          # The test will gracefully close the IDE instance if successful,
+          # but we still need to kill the IDE instance in case that test was not successful AND the IDE is still running.
+          function finish {
+            if ps -p $ide_pid >/dev/null 2>&1; then
+              kill $ide_pid
+            fi
+          }
+          trap finish EXIT
+
+          last_line=0
+          # Let's wait until Remote Robot plugin living within the IDE starts listening.
+          info 'Logs of gradle runIdeForUiTests'
+          while ! nc -z localhost 8080; do
+            sleep 0.5
+            tail -n+$((last_line+1)) $log
+            last_line=$(wc -l < $log)
           done
-          ./gradlew --no-daemon --stacktrace -i -PijVersion=$(IDEA_VERSION) test
+
+          info 'Logs of gradle test'
+          ./gradlew --info -PijVersion=$(IDEA_VERSION) test || {
+            info 'Logs of IDE under test'
+            cat /build/idea-sandbox/system/log/idea.log
+            die 'UI tests failed; inspect Gradle and IDE logs above'
+          }
         displayName: 'Run UI tests on $(IDEA_VERSION)'
         env:
           DISPLAY: ':10'
